
before_script:
    - echo "CI for signal, 2016-09-28"
    - smvn --version

default:
    script: 
        - smvn init
        - smvn bnt
        - smvn install
        - smvn deploy

default2:
    script: 
        - smvn init
        - smvn bnt
        - smvn install
        - smvn deploy
